<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite Test" duration-ms="17793" started-at="2017-09-09T07:25:31Z" finished-at="2017-09-09T07:25:49Z">
    <groups>
    </groups>
    <test name="DriverTest" duration-ms="17793" started-at="2017-09-09T07:25:31Z" finished-at="2017-09-09T07:25:49Z">
      <class name="com.bitm.newtours5th.Test.LoginTest">
        <test-method status="FAIL" signature="checkloginpagetitle()[pri:1, instance:com.bitm.newtours5th.Test.LoginTest@d8355a8]" name="checkloginpagetitle" duration-ms="16704" started-at="2017-09-09T13:25:31Z" finished-at="2017-09-09T13:25:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome: Mercury Tours as] but found [Welcome: Mercury Tours]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome: Mercury Tours as] but found [Welcome: Mercury Tours]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.bitm.newtours5th.Test.LoginTest.checkloginpagetitle(LoginTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkloginpagetitle -->
        <test-method status="PASS" signature="logintest()[pri:2, instance:com.bitm.newtours5th.Test.LoginTest@d8355a8]" name="logintest" duration-ms="1039" started-at="2017-09-09T13:25:48Z" finished-at="2017-09-09T13:25:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
      </class> <!-- com.bitm.newtours5th.Test.LoginTest -->
    </test> <!-- DriverTest -->
  </suite> <!-- Suite Test -->
</testng-results>
